server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd HH:mm:ss"
    mapper:
      default-view-inclusion: true

springdoc:
  version: 1.0
  packagesToScan: com.test.property.ordering.controller
  pathsToMatch: /test/**,
  api-docs:
    resolve-schema-properties: true  
#  swagger-ui:
#    operationsSorter: method
#    apisSorter: alpha


